### ISSUE TITLE
media links in tables not recognized / formatted correctly

### ISSUE THREAD

**Issue by tmo26** [ConX/dokuwiki-plugin-prettytables#4]
Dokuwiki: Release 2015-08-10a "Detritus"
Prettytables: 2012-09-01

Problem: Media links in tables are not well recognized by the prettytables plugin. Example line out of a bigger table:

Before prettytables:
    `| {{:media:datasheets:bcm6358.datasheet.pdf|BCM6358}} |`

After prettytables:
    `| {{:media:datasheets:bcm6358.datasheet.pdf   (many spaces)   | BCM6358}}|`
(I couldn't make the spaces show up here...)

Would be nice if that could be fixed, since currently, it does the opposite of making pretty ;-)

**Comment by ConX** [comment]
Thank you for the report! Let me know if the fix works for you as well.

**Comment by davemidd** [comment]
Please can you update the date in plugin.info.txt to match the date on the DokuWiki plugins page, otherwise the extension manager keeps showing that there is an update available, even after updating.  Thanks.

**Comment by ConX** [comment]
I forgot that :) Thanks

**Comment by tmo26** [comment]
Works for me as well.
Thanks for you efforts!
